name: integracion continua con node.js

on:
  push:

jobs:

  run:
   
    runs-on: ubuntu-latest
   
    steps:
      - name: 'Checkout ğŸš€'
      
        uses: actions/checkout@v4

      - name: 'Setup node âš™'
          
        uses: actions/setup-node@v4
        
        with:

          node-version: 16

      - name: ' instalacion dependenciasğŸ’»'
        
        run: npm ci

      - name: 'Build typescript ğŸ“Ÿ'

        run: npm run build

      - name: 'Run test âœ”'
       
        run: npm run test

     
  
